title: Installing Jupyter Notebook on a Raspberry Pi
hero_image: images/banner.png
description: installing-jupyter-notebook-on-a-raspberry-pi description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum: creator, programming-0, phys-comp-0, community-0
interests: " physical computing, robots "
technologies: "physical computing, python"
site_areas:
steps:
  - title: Installing
